profiles:
- config_maps:
  - content: source /workspace/.bashrc
    default_mode: '0660'
    key: bash-login-mlflow-coder-app
    mount_path: /workspace/.bash_login
    name: bash-login-mlflow-coder-app
    persist: false
    readonly: true
  - content: "#!/bin/bash\n\n# Function to display help\nshow_help () {\n    echo \"Usage: $0 [options]\"\n    echo -e \"\\nThis utility copies your local image pull secrets to your kubernetes namespace\\n\"\n    echo \"Options:\"\n    echo \"  --help         Display this help message\"\n    exit 1\n}\n\n# Check for the --help option\n[ \"$1\" == \"--help\" ] && show_help\n\n# Check if kubectl is installed\n[ ! command -v kubectl &> /dev/null ] && {\n    echo \"kubectl not found. Please install kubectl.\"\n    exit 1\n}\n\n# Function to check if a file exists\nfile_exists () {\n    if [ ! -f \"$1\" ]; then\n        echo \"$1 not found\"\n        exit 1\n    fi\n}\n\n# Check if the XDG_RUNTIME_DIR environment variable is set\nif [ -z \"$XDG_RUNTIME_DIR\" ]; then\n    echo \"XDG_RUNTIME_DIR environment variable is not set\"\n    exit 1\nfi\n\nAUTH_JSON_PATH=\"$XDG_RUNTIME_DIR/containers/auth.json\"\n\nfile_exists ${AUTH_JSON_PATH}\n\nSECRET_NAME=\"incluster-cr-secret\"\n\nkubectl delete secret \"${SECRET_NAME}\" &> /dev/null\n\nkubectl create secret generic \"${SECRET_NAME}\" --from-file=.dockerconfigjson=${AUTH_JSON_PATH} --type=kubernetes.io/dockerconfigjson &> /dev/null\n\nres=$?\n\n[ ${res} == 0 ] && { \n    echo \"Image pull secrets updated\" \n} || { \n    echo \"\"\n    exit 1 \n}"
    default_mode: '0755'
    key: copy-secrets
    mount_path: /usr/bin/copy-secrets
    name: copy-secrets-mlflow-coder-app
    persist: false
    readonly: true
  definition:
    default: false
    description: Code Server with MLflow deployed
    display_name: Coder + MLflow
    kubespawner_override:
      cpu_guarantee: 1
      cpu_limit: 2
      extra_resource_guarantees: {}
      extra_resource_limits: {}
      image: ghcr.io/eoepca/pde-code-server:latest-dev
      mem_guarantee: 4G
      mem_limit: 6G
    slug: mlflow_coder_app
  env_from_config_maps: []
  env_from_secrets: []
  groups:
  - group-2
  id: profile_mlflow_coder_app
  image_pull_secrets:
  - data: ewoJImF1dGhzIjogewoJCSJjci50ZXJyYWR1ZS5jb20iOiB7CgkJCSJhdXRoIjogIlptSnlhWFJ2T21ZNVZFNUNaVTlIVEE9PSIKCQl9Cgl9Cn0=
    name: incluster-cr-secret
    persist: false
  init_containers: []
  manifests:
  - content: []
    key: mlflow
    name: mlflow-mlflow-coder-app
    persist: false
  node_selector: {}
  pod_env_vars:
    CWLTOOL_OPTIONS: --podman
    HOME: /workspace
    NAMESPACE: '{{ namespace }}'
    XDG_CONFIG_HOME: /workspace/.local
    XDG_DATA_HOME: /workspace/.local/share/
    XDG_RUNTIME_DIR: /workspace/.local
  role_bindings:
  - name: log-reader-role-binding-mlflow-coder-app
    persist: false
    role:
      api_groups:
      - ''
      name: log-reader-role-mlflow-coder-app
      resources:
      - pods
      - pods/log
      verbs:
      - get
      - list
      - watch
    subjects:
    - kind: ServiceAccount
      name: default
  - name: pod-reader-role-binding-mlflow-coder-app
    persist: false
    role:
      api_groups:
      - ''
      name: pod-manager-role-mlflow-coder-app
      resources:
      - pods
      verbs:
      - create
      - patch
      - delete
      - list
      - watch
      - get
    subjects:
    - kind: ServiceAccount
      name: default
  - name: pod-exec-role-binding-mlflow-coder-app
    persist: false
    role:
      api_groups:
      - ''
      name: pod-exec-role-mlflow-coder-app
      resources:
      - pods/exec
      verbs:
      - create
    subjects:
    - kind: ServiceAccount
      name: default
  - name: secret-patcher-role-binding-mlflow-coder-app
    persist: false
    role:
      api_groups:
      - ''
      name: secret-patcher-role-mlflow-coder-app
      resources:
      - secrets
      verbs:
      - create
      - delete
    subjects:
    - kind: ServiceAccount
      name: default
  - name: job-submitter-role-binding-mlflow-coder-app
    persist: false
    role:
      api_groups:
      - batch
      name: job-submitter-role-mlflow-coder-app
      resources:
      - jobs
      verbs:
      - create
      - delete
      - list
      - watch
      - get
    subjects:
    - kind: ServiceAccount
      name: default
  secret_mounts: []
  volumes:
  - access_modes:
    - ReadWriteMany
    claim_name: calrissian-claim
    name: calrissian-volume
    persist: false
    size: 30Gi
    storage_class: standard
    volume_mount:
      mount_path: /calrissian
      name: calrissian-volume
  - access_modes:
    - ReadWriteOnce
    claim_name: workspace-claim
    name: workspace-volume
    persist: true
    size: 15Gi
    storage_class: standard
    volume_mount:
      mount_path: /workspace
      name: workspace-volume
