apiVersion: skaffold/v4beta9
kind: Config

deploy:
  helm:
    releases:
      - name: jupyterhub
        remoteChart: eoepca-dev/application-hub
        namespace: jupyter
        version: 4.0.2
        createNamespace: true
        valuesFiles: []
        setValueTemplates:
          jupyterhub.hub.image.name: ghcr.io/eoepca/application-hub
          jupyterhub.hub.image.tag: 1.5.1
        setValues:
          jupyterhub.hub.image.pullSecrets: []
          jupyterhub.hub.db.pvc.storageClassName: standard
          jupyterhub.hub.extraEnv.STORAGE_CLASS: standard
          jupyterhub.proxy.secretToken: "032d5bfe141a7eab86d57587879b33c5d168617cacb339823d7f47fe2933f880"
          jupyterhub.hub.extraEnv.APP_HUB_NAMESPACE: jupyter
          jupyterhub.hub.networkPolicy.enabled: false
        setFiles:
          configYml: config/config.yml
          jupyterConfig: config/jupyterhub_config.py
      
      - name: crossplane
        remoteChart: crossplane-stable/crossplane
        namespace: crossplane-system
        createNamespace: true
        version: 2.2.0
        
    hooks:
      before:
        - host:
            command:
              [
                "sh",
                "-c",
                "helm repo add eoepca-dev https://eoepca.github.io/helm-charts && helm repo update || helm repo update",
              ]
        - host:
            command:
              [
                "sh",
                "-c",
                "helm repo add crossplane-stable https://charts.crossplane.io/stable && helm repo update || helm repo update",
              ]
        - host:
            command: ["sh", "-c", ".skaffold/scripts/get-crds.sh"]

manifests:
  rawYaml:
  - .skaffold/manifests/cluster-role-binding.yaml
  - .skaffold/manifests/script.yaml
  - .skaffold/manifests/job.yaml

portForward:
- resourceType: service
  resourceName: application-hub-proxy-public
  namespace: jupyter
  port: 80 
  localPort: 8000 

profiles:

  - name: baseline

    patches:
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates/jupyterhub.hub.image.name
        value: ghcr.io/eoepca/application-hub
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates/jupyterhub.hub.image.tag
        value: 1.5.2
      - op: add
        path: /deploy/helm/releases/0/setFiles/configYml
        value: config.yaml


  - name: develop

    patches:
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates/jupyterhub.hub.image.name
        value: ghcr.io/eoepca/application-hub
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates/jupyterhub.hub.image.tag
        value: latest-dev
      - op: add
        path: /deploy/helm/releases/0/setFiles/configYml
        value: config.yaml

  - name: main
  
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates/jupyterhub.hub.image.name
        value: ghcr.io/eoepca/application-hub
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates/jupyterhub.hub.image.tag
        value: latest

