version: '3'

tasks:
      
  test:
    desc: Run tests
    cmds:
      - hatch run test:test-show-setup

  check:
    desc: Run code quality checks
    cmds:
      - hatch run dev:check

  lint:
    desc: Run linters
    cmds:
      - hatch run dev:lint

  serve-doc:
    desc: Serve documentation locally
    cmds:
      - hatch run docs:serve