#!/bin/bash

# Function to display help
show_help () {
    echo "Usage: $0 [options]"
    echo -e "\nThis utility copies your local image pull secrets to your kubernetes namespace\n"
    echo "Options:"
    echo "  --help         Display this help message"
    exit 1
}

# Check for the --help option
[ "$1" == "--help" ] && show_help

# Check if kubectl is installed
[ ! command -v kubectl &> /dev/null ] && {
    echo "kubectl not found. Please install kubectl."
    exit 1
}

# Function to check if a file exists
file_exists () {
    if [ ! -f "$1" ]; then
        echo "$1 not found"
        exit 1
    fi
}

# Check if the XDG_RUNTIME_DIR environment variable is set
if [ -z "$XDG_RUNTIME_DIR" ]; then
    echo "XDG_RUNTIME_DIR environment variable is not set"
    exit 1
fi

AUTH_JSON_PATH="$XDG_RUNTIME_DIR/containers/auth.json"

file_exists ${AUTH_JSON_PATH}

SECRET_NAME="incluster-cr-secret"

kubectl delete secret "${SECRET_NAME}" &> /dev/null

kubectl create secret generic "${SECRET_NAME}" --from-file=.dockerconfigjson=${AUTH_JSON_PATH} --type=kubernetes.io/dockerconfigjson &> /dev/null

res=$?

[ ${res} == 0 ] && {
    echo "Image pull secrets updated"
} || {
    echo ""
    exit 1
}
